### ISSUE TITLE
python3.5 pip install 

### ISSUE THREAD

**Issue by NikolayTV** [menpo/menpo#813]
when i try to install on python3.5:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e8dgwkq1/menpo/setup.py", line 16, in <module>
        for r in site.getsitepackages() if
    AttributeError: module 'site' has no attribute 'getsitepackages'
    
    ---

python3.6 pip install - works well 
but menpowidgets dont work with 3.6

**Comment by NikolayTV** [comment]
with conda everything is well

**Comment by ktho22** [comment]
it seems the problem of venv
[https://github.com/pypa/virtualenv/issues/737](https://github.com/pypa/virtualenv/issues/737)

**Comment by ktho22** [comment]
Did you use virtualenv?
I had same error using virtualenv, since venv doesn't support `site.getsitepackages()` [https://github.com/pypa/virtualenv/issues/737](https://github.com/pypa/virtualenv/issues/737)

**Comment by NikolayTV** [comment]
it doesnot work with pip install. you should install it with conda
